# Generated by Django 5.1.3 on 2024-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_managers_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='scopes',
            field=models.JSONField(default=list),
        ),
    ]
