# Generated by Django 5.1.3 on 2024-11-24 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0012_add_token_checksum'),
        ('users', '0003_role_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAccessToken',
            fields=[
                ('accesstoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('oauth2_provider.accesstoken',),
        ),
    ]
