# Generated by Django 5.1.3 on 2024-11-24 08:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=255)),
                ('expired_date', models.DateField(verbose_name='Expiry Date')),
                ('main_image', models.CharField(max_length=255)),
                ('sub_image_1', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_image_2', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='warehouse.location')),
            ],
            options={
                'verbose_name': 'Finished Product',
                'verbose_name_plural': 'Finished Products',
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=255)),
                ('expired_date', models.DateField(verbose_name='Expiry Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='warehouse.location')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
    ]
